package com.example.perfume_budget.enums;

public enum AccountCategory {
    CASH,
    MOBILE_MONEY,
    COGS,
    INVENTORY,
    SALES_REVENUE,
    DISCOUNT_EXPENSE,
    ACCOUNTS_PAYABLE,
    INVENTORY_DECREASE,
    INVENTORY_INCREASE,
    TAX_PAYABLE,
    REFUND_PAYABLE,
    COUPON_EXPENSE,
    MARKETING_EXPENSE,
    LOGISTICS_EXPENSE,
    MISCELLANEOUS_EXPENSE,
    OWNERS_EQUITY,
    OWNERS_CAPITAL,
    RETAINED_EARNINGS,
    LOANS_PAYABLE,
    INVESTMENT_INCOME,
    GENERAL_EXPENSE,
    INVENTORY_VARIANCE,
    INVENTORY_REVALUATION
}
