CREATE TABLE cart_items
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cart_id       BIGINT                                  NOT NULL,
    product_id    BIGINT                                  NOT NULL,
    quantity      INTEGER                                 NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    amount        DECIMAL(19, 2),
    currency_code VARCHAR(3),
    CONSTRAINT pk_cart_items PRIMARY KEY (id)
);

CREATE TABLE carts
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_carts PRIMARY KEY (id)
);

CREATE TABLE categories
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    slug        VARCHAR(255)                            NOT NULL,
    description TEXT,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_categories PRIMARY KEY (id)
);

CREATE TABLE coupons
(
    id                               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code                             VARCHAR(255)                            NOT NULL,
    discount_type                    VARCHAR(255)                            NOT NULL,
    discount_value                   DECIMAL                                 NOT NULL,
    maximum_discount_amount          DECIMAL,
    minimum_cart_amount_for_discount DECIMAL,
    usage_limit                      INTEGER                                 NOT NULL,
    usage_count                      INTEGER,
    per_user_usage_limit             INTEGER,
    is_active                        BOOLEAN                                 NOT NULL,
    start_date                       date                                    NOT NULL,
    expiration_date                  date                                    NOT NULL,
    created_at                       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at                       TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_coupons PRIMARY KEY (id)
);

CREATE TABLE delivery_details
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id                BIGINT                                  NOT NULL,
    recipient_name         VARCHAR(255)                            NOT NULL,
    phone_number           VARCHAR(255)                            NOT NULL,
    alternate_phone_number VARCHAR(255),
    address_line1          VARCHAR(255)                            NOT NULL,
    address_line2          VARCHAR(255),
    city                   VARCHAR(255)                            NOT NULL,
    region                 VARCHAR(255)                            NOT NULL,
    landmark               VARCHAR(255),
    label                  VARCHAR(255)                            NOT NULL,
    is_default             BOOLEAN                                 NOT NULL,
    created_at             TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at             TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_delivery_details PRIMARY KEY (id)
);

CREATE TABLE feature_flags
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    feature_key VARCHAR(255)                            NOT NULL,
    audience    VARCHAR(255)                            NOT NULL,
    enabled     BOOLEAN                                 NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_feature_flags PRIMARY KEY (id)
);

CREATE TABLE front_desk_permission_templates
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    permission VARCHAR(255)                            NOT NULL,
    enabled    BOOLEAN                                 NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_front_desk_permission_templates PRIMARY KEY (id)
);

CREATE TABLE front_desk_user_permission_overrides
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    permission VARCHAR(255)                            NOT NULL,
    allowed    BOOLEAN                                 NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_front_desk_user_permission_overrides PRIMARY KEY (id)
);

CREATE TABLE inventory_allocations
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    layer_id           BIGINT                                  NOT NULL,
    product_id         BIGINT                                  NOT NULL,
    reference_type     VARCHAR(255)                            NOT NULL,
    reference_id       VARCHAR(255)                            NOT NULL,
    reference_line_key VARCHAR(255)                            NOT NULL,
    quantity           INTEGER                                 NOT NULL,
    unit_cost          DECIMAL(19, 2)                          NOT NULL,
    unit_selling_price DECIMAL(19, 2)                          NOT NULL,
    currency_code      VARCHAR(255)                            NOT NULL,
    status             VARCHAR(255)                            NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_inventory_allocations PRIMARY KEY (id)
);

CREATE TABLE inventory_layers
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_id         BIGINT                                  NOT NULL,
    source_type        VARCHAR(255)                            NOT NULL,
    source_reference   VARCHAR(255),
    note               TEXT,
    received_quantity  INTEGER                                 NOT NULL,
    remaining_quantity INTEGER                                 NOT NULL,
    unit_cost          DECIMAL(19, 2)                          NOT NULL,
    unit_selling_price DECIMAL(19, 2)                          NOT NULL,
    currency_code      VARCHAR(255)                            NOT NULL,
    received_at        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by         VARCHAR(255),
    created_at         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_inventory_layers PRIMARY KEY (id)
);

CREATE TABLE inventory_movements
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    layer_id           BIGINT,
    product_id         BIGINT                                  NOT NULL,
    movement_type      VARCHAR(255)                            NOT NULL,
    reference_type     VARCHAR(255)                            NOT NULL,
    reference_id       VARCHAR(255)                            NOT NULL,
    reference_line_key VARCHAR(255),
    quantity           INTEGER                                 NOT NULL,
    unit_cost          DECIMAL(19, 2)                          NOT NULL,
    unit_selling_price DECIMAL(19, 2)                          NOT NULL,
    currency_code      VARCHAR(255)                            NOT NULL,
    note               TEXT,
    recorded_by        VARCHAR(255),
    created_at         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_inventory_movements PRIMARY KEY (id)
);

CREATE TABLE journal_entries
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    entry_number     VARCHAR(255)                            NOT NULL,
    description      VARCHAR(255)                            NOT NULL,
    type             VARCHAR(255)                            NOT NULL,
    reference_type   VARCHAR(255),
    reference_id     VARCHAR(255),
    is_manual        BOOLEAN                                 NOT NULL,
    recorded_by      VARCHAR(255),
    transaction_date TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_journal_entries PRIMARY KEY (id)
);

CREATE TABLE journal_entry_lines
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    journal_entry_id BIGINT                                  NOT NULL,
    account_id       BIGINT                                  NOT NULL,
    entry_type       VARCHAR(255)                            NOT NULL,
    amount           DECIMAL(19, 2)                          NOT NULL,
    description      VARCHAR(255),
    CONSTRAINT pk_journal_entry_lines PRIMARY KEY (id)
);

CREATE TABLE ledger_accounts
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code      VARCHAR(255)                            NOT NULL,
    name      VARCHAR(255)                            NOT NULL,
    type      VARCHAR(255)                            NOT NULL,
    category  VARCHAR(255)                            NOT NULL,
    is_active BOOLEAN                                 NOT NULL,
    balance   DECIMAL(19, 2)                          NOT NULL,
    CONSTRAINT pk_ledger_accounts PRIMARY KEY (id)
);

CREATE TABLE notification_recipients
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    notification_id BIGINT                                  NOT NULL,
    user_id         BIGINT                                  NOT NULL,
    is_read         BOOLEAN                                 NOT NULL,
    read_at         TIMESTAMP WITHOUT TIME ZONE,
    delivered_at    TIMESTAMP WITHOUT TIME ZONE,
    created_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_notification_recipients PRIMARY KEY (id)
);

CREATE TABLE notifications
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type           VARCHAR(64)                             NOT NULL,
    title          VARCHAR(128)                            NOT NULL,
    message        VARCHAR(512)                            NOT NULL,
    reference_type VARCHAR(64),
    reference_id   VARCHAR(128),
    created_at     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_notifications PRIMARY KEY (id)
);

CREATE TABLE order_items
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id             BIGINT,
    product_id           BIGINT                                  NOT NULL,
    product_name         VARCHAR(255)                            NOT NULL,
    sku                  VARCHAR(255),
    quantity             INTEGER                                 NOT NULL,
    created_at           TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at           TIMESTAMP WITHOUT TIME ZONE,
    unit_price_amount    DECIMAL,
    unit_price_currency  VARCHAR(255),
    cost_price_amount    DECIMAL,
    cost_price_currency  VARCHAR(255),
    total_price_amount   DECIMAL,
    total_price_currency VARCHAR(255),
    CONSTRAINT pk_order_items PRIMARY KEY (id)
);

CREATE TABLE order_taxes
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id         BIGINT                                  NOT NULL,
    tax_name         VARCHAR(255)                            NOT NULL,
    tax_code         VARCHAR(255)                            NOT NULL,
    tax_rate         DECIMAL(5, 2)                           NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at       TIMESTAMP WITHOUT TIME ZONE,
    taxable_amount   DECIMAL,
    taxable_currency VARCHAR(255),
    tax_amount       DECIMAL,
    tax_currency     VARCHAR(255),
    CONSTRAINT pk_order_taxes PRIMARY KEY (id)
);

CREATE TABLE orders
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_number             VARCHAR(255)                            NOT NULL,
    user_id                  BIGINT,
    status                   VARCHAR(255),
    delivery_status          VARCHAR(255),
    payment_reference        VARCHAR(255),
    coupon_id                BIGINT,
    created_at               TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at               TIMESTAMP WITHOUT TIME ZONE,
    subtotal_amount          DECIMAL,
    subtotal_currency        VARCHAR(255),
    discount_amount          DECIMAL,
    discount_amount_currency VARCHAR(255),
    total_amount             DECIMAL,
    total_amount_currency    VARCHAR(255),
    total_tax_amount         DECIMAL,
    tax_currency             VARCHAR(255),
    CONSTRAINT pk_orders PRIMARY KEY (id)
);

CREATE TABLE payments
(
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    system_reference           VARCHAR(255)                            NOT NULL,
    provider_payment_reference VARCHAR(255),
    order_id                   BIGINT                                  NOT NULL,
    provider                   VARCHAR(255)                            NOT NULL,
    payment_method             VARCHAR(255),
    amount                     DECIMAL(19, 2)                          NOT NULL,
    currency                   VARCHAR(255)                            NOT NULL,
    status                     VARCHAR(255)                            NOT NULL,
    customer_email             VARCHAR(255)                            NOT NULL,
    failure_reason             VARCHAR(255),
    gateway_response           JSONB,
    paid_at                    TIMESTAMP WITHOUT TIME ZONE,
    created_at                 TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at                 TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_payments PRIMARY KEY (id)
);

CREATE TABLE product_families
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    family_code  VARCHAR(255)                            NOT NULL,
    name         VARCHAR(255)                            NOT NULL,
    brand        VARCHAR(255),
    base_unit_id BIGINT,
    CONSTRAINT pk_product_families PRIMARY KEY (id)
);

CREATE TABLE products
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version             BIGINT,
    name                VARCHAR(255)                            NOT NULL,
    brand               VARCHAR(255),
    size                VARCHAR(255),
    slug                VARCHAR(255)                            NOT NULL,
    description         TEXT,
    short_description   VARCHAR(255),
    sku                 VARCHAR(255)                            NOT NULL,
    stock_quantity      INTEGER                                 NOT NULL,
    sold_count          INTEGER,
    low_stock_threshold INTEGER,
    category_id         BIGINT,
    image_url           VARCHAR(255),
    is_active           BOOLEAN,
    is_enlisted         BOOLEAN,
    is_featured         BOOLEAN,
    weight              DECIMAL,
    family_id           BIGINT,
    unit_of_measure_id  BIGINT,
    conversion_factor   INTEGER,
    is_base_unit        BOOLEAN,
    view_count          BIGINT,
    add_to_cart_count   BIGINT,
    created_at          TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at          TIMESTAMP WITHOUT TIME ZONE,
    price_amount        DECIMAL,
    price_currency      VARCHAR(255),
    cost_price_amount   DECIMAL,
    cost_price_currency VARCHAR(255),
    CONSTRAINT pk_products PRIMARY KEY (id)
);

CREATE TABLE profiles
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id      BIGINT,
    phone_number VARCHAR(255),
    address      VARCHAR(255),
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_profiles PRIMARY KEY (id)
);

CREATE TABLE site_visits
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ip_address VARCHAR(255)                            NOT NULL,
    page       VARCHAR(255)                            NOT NULL,
    visit_date date                                    NOT NULL,
    CONSTRAINT pk_site_visits PRIMARY KEY (id)
);

CREATE TABLE stock_conversions
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    conversion_number VARCHAR(255)                            NOT NULL,
    from_product_id   BIGINT                                  NOT NULL,
    to_product_id     BIGINT                                  NOT NULL,
    from_quantity     INTEGER                                 NOT NULL,
    to_quantity       INTEGER                                 NOT NULL,
    from_cost_value   DECIMAL(19, 4)                          NOT NULL,
    to_cost_value     DECIMAL(19, 4)                          NOT NULL,
    variance_amount   DECIMAL(19, 4)                          NOT NULL,
    direction         VARCHAR(255)                            NOT NULL,
    converted_by_id   BIGINT                                  NOT NULL,
    notes             TEXT,
    converted_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_stock_conversions PRIMARY KEY (id)
);

CREATE TABLE taxes
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    code        VARCHAR(255)                            NOT NULL,
    rate        DECIMAL(5, 2)                           NOT NULL,
    is_active   BOOLEAN                                 NOT NULL,
    is_compound BOOLEAN                                 NOT NULL,
    apply_order INTEGER                                 NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_taxes PRIMARY KEY (id)
);

CREATE TABLE units_of_measure
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code VARCHAR(10)                             NOT NULL,
    name VARCHAR(50)                             NOT NULL,
    CONSTRAINT pk_units_of_measure PRIMARY KEY (id)
);

CREATE TABLE users
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    full_name      VARCHAR(255)                            NOT NULL,
    email          VARCHAR(255)                            NOT NULL,
    password       VARCHAR(255)                            NOT NULL,
    roles          VARCHAR(255)                            NOT NULL,
    is_active      BOOLEAN,
    auth_provider  VARCHAR(255),
    provider_id    VARCHAR(255),
    email_verified BOOLEAN,
    image_url      VARCHAR(512),
    created_at     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at     TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE walk_in_customers
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(255),
    phone        VARCHAR(255),
    email        VARCHAR(255),
    is_anonymous BOOLEAN                                 NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_walk_in_customers PRIMARY KEY (id)
);

CREATE TABLE walk_in_order_items
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    walk_in_order_id BIGINT                                  NOT NULL,
    product_id       BIGINT                                  NOT NULL,
    product_name     VARCHAR(255)                            NOT NULL,
    sku              VARCHAR(255)                            NOT NULL,
    quantity         INTEGER                                 NOT NULL,
    unit_price       DECIMAL(19, 2)                          NOT NULL,
    cost_price       DECIMAL(19, 2)                          NOT NULL,
    total_price      DECIMAL(19, 2)                          NOT NULL,
    CONSTRAINT pk_walk_in_order_items PRIMARY KEY (id)
);

CREATE TABLE walk_in_order_taxes
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    walk_in_order_id BIGINT                                  NOT NULL,
    tax_name         VARCHAR(255)                            NOT NULL,
    tax_code         VARCHAR(255)                            NOT NULL,
    tax_rate         DECIMAL(5, 2)                           NOT NULL,
    taxable_amount   DECIMAL(19, 2)                          NOT NULL,
    tax_amount       DECIMAL(19, 2)                          NOT NULL,
    CONSTRAINT pk_walk_in_order_taxes PRIMARY KEY (id)
);

CREATE TABLE walk_in_orders
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_number          VARCHAR(255)                            NOT NULL,
    registered_user_id    BIGINT,
    walk_in_customer_id   BIGINT,
    processed_by_id       BIGINT                                  NOT NULL,
    discount_type         VARCHAR(255),
    discount_value        DECIMAL(19, 2),
    payment_method        VARCHAR(255)                            NOT NULL,
    split_cash_amount     DECIMAL(19, 2),
    split_mobile_amount   DECIMAL(19, 2),
    status                VARCHAR(255)                            NOT NULL,
    receipt_printed       BOOLEAN                                 NOT NULL,
    created_at            TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at            TIMESTAMP WITHOUT TIME ZONE,
    subtotal_amount       DECIMAL,
    subtotal_currency     VARCHAR(255),
    discount_amount       DECIMAL,
    discount_currency     VARCHAR(255),
    total_tax_amount      DECIMAL,
    total_tax_currency    VARCHAR(255),
    total_amount          DECIMAL,
    total_currency        VARCHAR(255),
    amount_paid           DECIMAL,
    amount_paid_currency  VARCHAR(255),
    change_given          DECIMAL,
    change_given_currency VARCHAR(255),
    CONSTRAINT pk_walk_in_orders PRIMARY KEY (id)
);

ALTER TABLE carts
    ADD CONSTRAINT uc_carts_user UNIQUE (user_id);

ALTER TABLE categories
    ADD CONSTRAINT uc_categories_slug UNIQUE (slug);

ALTER TABLE coupons
    ADD CONSTRAINT uc_coupons_code UNIQUE (code);

ALTER TABLE cart_items
    ADD CONSTRAINT uc_e020537f6d07b2305eddbe2b3 UNIQUE (cart_id, product_id);

ALTER TABLE journal_entries
    ADD CONSTRAINT uc_journal_entries_entrynumber UNIQUE (entry_number);

ALTER TABLE ledger_accounts
    ADD CONSTRAINT uc_ledger_accounts_code UNIQUE (code);

ALTER TABLE orders
    ADD CONSTRAINT uc_orders_ordernumber UNIQUE (order_number);

ALTER TABLE payments
    ADD CONSTRAINT uc_payments_providerpaymentreference UNIQUE (provider_payment_reference);

ALTER TABLE payments
    ADD CONSTRAINT uc_payments_systemreference UNIQUE (system_reference);

ALTER TABLE product_families
    ADD CONSTRAINT uc_product_families_base_unit UNIQUE (base_unit_id);

ALTER TABLE product_families
    ADD CONSTRAINT uc_product_families_family_code UNIQUE (family_code);

ALTER TABLE products
    ADD CONSTRAINT uc_products_sku UNIQUE (sku);

ALTER TABLE products
    ADD CONSTRAINT uc_products_slug UNIQUE (slug);

ALTER TABLE profiles
    ADD CONSTRAINT uc_profiles_user UNIQUE (user_id);

ALTER TABLE stock_conversions
    ADD CONSTRAINT uc_stock_conversions_conversion_number UNIQUE (conversion_number);

ALTER TABLE units_of_measure
    ADD CONSTRAINT uc_units_of_measure_code UNIQUE (code);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE walk_in_orders
    ADD CONSTRAINT uc_walk_in_orders_ordernumber UNIQUE (order_number);

ALTER TABLE feature_flags
    ADD CONSTRAINT uk_feature_flag_key_audience UNIQUE (feature_key, audience);

ALTER TABLE front_desk_permission_templates
    ADD CONSTRAINT uk_front_desk_permission_template_permission UNIQUE (permission);

ALTER TABLE front_desk_user_permission_overrides
    ADD CONSTRAINT uk_front_desk_user_permission_override UNIQUE (user_id, permission);

ALTER TABLE notification_recipients
    ADD CONSTRAINT uk_notification_recipient_user UNIQUE (notification_id, user_id);

CREATE UNIQUE INDEX idx_email ON users (email);

CREATE INDEX idx_family_code ON product_families (family_code);

CREATE INDEX idx_inventory_alloc_product ON inventory_allocations (product_id, status);

CREATE INDEX idx_inventory_alloc_ref ON inventory_allocations (reference_type, reference_id, status);

CREATE INDEX idx_inventory_layer_product_received ON inventory_layers (product_id, received_at, id);

CREATE INDEX idx_inventory_layer_product_remaining ON inventory_layers (product_id, remaining_quantity);

CREATE INDEX idx_inventory_move_product ON inventory_movements (product_id, created_at);

CREATE INDEX idx_inventory_move_ref ON inventory_movements (reference_type, reference_id);

CREATE INDEX idx_notification_recipient_user_read_created ON notification_recipients (user_id, is_read, created_at);

CREATE INDEX idx_product_name ON products (name);

CREATE INDEX idx_product_price ON products (price_amount);

ALTER TABLE carts
    ADD CONSTRAINT FK_CARTS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE cart_items
    ADD CONSTRAINT FK_CART_ITEMS_ON_CART FOREIGN KEY (cart_id) REFERENCES carts (id);

ALTER TABLE cart_items
    ADD CONSTRAINT FK_CART_ITEMS_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES products (id);

ALTER TABLE delivery_details
    ADD CONSTRAINT FK_DELIVERY_DETAILS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE front_desk_user_permission_overrides
    ADD CONSTRAINT FK_FRONT_DESK_USER_PERMISSION_OVERRIDES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE inventory_allocations
    ADD CONSTRAINT FK_INVENTORY_ALLOCATIONS_ON_LAYER FOREIGN KEY (layer_id) REFERENCES inventory_layers (id);

ALTER TABLE inventory_allocations
    ADD CONSTRAINT FK_INVENTORY_ALLOCATIONS_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES products (id);

ALTER TABLE inventory_layers
    ADD CONSTRAINT FK_INVENTORY_LAYERS_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES products (id);

ALTER TABLE inventory_movements
    ADD CONSTRAINT FK_INVENTORY_MOVEMENTS_ON_LAYER FOREIGN KEY (layer_id) REFERENCES inventory_layers (id);

ALTER TABLE inventory_movements
    ADD CONSTRAINT FK_INVENTORY_MOVEMENTS_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES products (id);

ALTER TABLE journal_entry_lines
    ADD CONSTRAINT FK_JOURNAL_ENTRY_LINES_ON_ACCOUNT FOREIGN KEY (account_id) REFERENCES ledger_accounts (id);

ALTER TABLE journal_entry_lines
    ADD CONSTRAINT FK_JOURNAL_ENTRY_LINES_ON_JOURNAL_ENTRY FOREIGN KEY (journal_entry_id) REFERENCES journal_entries (id);

ALTER TABLE notification_recipients
    ADD CONSTRAINT FK_NOTIFICATION_RECIPIENTS_ON_NOTIFICATION FOREIGN KEY (notification_id) REFERENCES notifications (id);

ALTER TABLE notification_recipients
    ADD CONSTRAINT FK_NOTIFICATION_RECIPIENTS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE orders
    ADD CONSTRAINT FK_ORDERS_ON_COUPON FOREIGN KEY (coupon_id) REFERENCES coupons (id);

ALTER TABLE orders
    ADD CONSTRAINT FK_ORDERS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE order_items
    ADD CONSTRAINT FK_ORDER_ITEMS_ON_ORDER FOREIGN KEY (order_id) REFERENCES orders (id);

ALTER TABLE order_taxes
    ADD CONSTRAINT FK_ORDER_TAXES_ON_ORDER FOREIGN KEY (order_id) REFERENCES orders (id);

ALTER TABLE payments
    ADD CONSTRAINT FK_PAYMENTS_ON_ORDER FOREIGN KEY (order_id) REFERENCES orders (id);

ALTER TABLE products
    ADD CONSTRAINT FK_PRODUCTS_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES categories (id);

CREATE INDEX idx_product_category ON products (category_id);

ALTER TABLE products
    ADD CONSTRAINT FK_PRODUCTS_ON_FAMILY FOREIGN KEY (family_id) REFERENCES product_families (id);

ALTER TABLE products
    ADD CONSTRAINT FK_PRODUCTS_ON_UNIT_OF_MEASURE FOREIGN KEY (unit_of_measure_id) REFERENCES units_of_measure (id);

ALTER TABLE product_families
    ADD CONSTRAINT FK_PRODUCT_FAMILIES_ON_BASE_UNIT FOREIGN KEY (base_unit_id) REFERENCES products (id);

ALTER TABLE profiles
    ADD CONSTRAINT FK_PROFILES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE stock_conversions
    ADD CONSTRAINT FK_STOCK_CONVERSIONS_ON_CONVERTED_BY FOREIGN KEY (converted_by_id) REFERENCES users (id);

ALTER TABLE stock_conversions
    ADD CONSTRAINT FK_STOCK_CONVERSIONS_ON_FROM_PRODUCT FOREIGN KEY (from_product_id) REFERENCES products (id);

ALTER TABLE stock_conversions
    ADD CONSTRAINT FK_STOCK_CONVERSIONS_ON_TO_PRODUCT FOREIGN KEY (to_product_id) REFERENCES products (id);

ALTER TABLE walk_in_orders
    ADD CONSTRAINT FK_WALK_IN_ORDERS_ON_PROCESSED_BY FOREIGN KEY (processed_by_id) REFERENCES users (id);

ALTER TABLE walk_in_orders
    ADD CONSTRAINT FK_WALK_IN_ORDERS_ON_REGISTERED_USER FOREIGN KEY (registered_user_id) REFERENCES users (id);

ALTER TABLE walk_in_orders
    ADD CONSTRAINT FK_WALK_IN_ORDERS_ON_WALK_IN_CUSTOMER FOREIGN KEY (walk_in_customer_id) REFERENCES walk_in_customers (id);

ALTER TABLE walk_in_order_items
    ADD CONSTRAINT FK_WALK_IN_ORDER_ITEMS_ON_WALK_IN_ORDER FOREIGN KEY (walk_in_order_id) REFERENCES walk_in_orders (id);

ALTER TABLE walk_in_order_taxes
    ADD CONSTRAINT FK_WALK_IN_ORDER_TAXES_ON_WALK_IN_ORDER FOREIGN KEY (walk_in_order_id) REFERENCES walk_in_orders (id);