-- Product-specific discount (nullable; active only within [discount_start_at, discount_end_at])
ALTER TABLE products
    ADD COLUMN discount_type     VARCHAR(20),
    ADD COLUMN discount_value    DECIMAL(19, 2),
    ADD COLUMN discount_start_at TIMESTAMP WITHOUT TIME ZONE,
    ADD COLUMN discount_end_at   TIMESTAMP WITHOUT TIME ZONE;

-- Shop-wide (store-wide) percentage discount, time-boxed
CREATE TABLE shop_wide_discounts
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    label               VARCHAR(255),
    discount_percentage DECIMAL(19, 2)                          NOT NULL,
    start_at            TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    end_at              TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    is_active           BOOLEAN                                 NOT NULL,
    created_at          TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at          TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_shop_wide_discounts PRIMARY KEY (id)
);

-- Speeds up the "active now" lookup
CREATE INDEX idx_shop_wide_discount_active
    ON shop_wide_discounts (is_active, start_at, end_at);
