-- Multi-storeroom inventory location tracking.
-- Physical location ledger alongside the global FIFO cost engine:
-- per-location balances, auditable transfer log, shop-floor restock alerting.

CREATE TABLE storage_locations
(
    id                             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                           VARCHAR(128)                            NOT NULL,
    type                           VARCHAR(32)                             NOT NULL,
    active                         BOOLEAN                                 NOT NULL DEFAULT TRUE,
    low_stock_threshold            INTEGER,
    is_default_receiving           BOOLEAN                                 NOT NULL DEFAULT FALSE,
    is_walk_in_sale_source         BOOLEAN                                 NOT NULL DEFAULT FALSE,
    is_ecommerce_fulfilment_source BOOLEAN                                 NOT NULL DEFAULT FALSE,
    version                        BIGINT                                  NOT NULL DEFAULT 0,
    created_at                     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at                     TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_storage_locations PRIMARY KEY (id)
);

ALTER TABLE storage_locations
    ADD CONSTRAINT uk_storage_locations_name UNIQUE (name);

-- At most one location may hold each default role.
CREATE UNIQUE INDEX uq_storage_locations_default_receiving
    ON storage_locations (is_default_receiving) WHERE is_default_receiving;
CREATE UNIQUE INDEX uq_storage_locations_walk_in_sale_source
    ON storage_locations (is_walk_in_sale_source) WHERE is_walk_in_sale_source;
CREATE UNIQUE INDEX uq_storage_locations_ecommerce_fulfilment_source
    ON storage_locations (is_ecommerce_fulfilment_source) WHERE is_ecommerce_fulfilment_source;

CREATE TABLE location_stock
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_id       BIGINT                                  NOT NULL,
    location_id      BIGINT                                  NOT NULL,
    quantity_on_hand INTEGER                                 NOT NULL DEFAULT 0,
    version          BIGINT                                  NOT NULL DEFAULT 0,
    created_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at       TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_location_stock PRIMARY KEY (id)
);

ALTER TABLE location_stock
    ADD CONSTRAINT uk_location_stock_product_location UNIQUE (product_id, location_id);

ALTER TABLE location_stock
    ADD CONSTRAINT FK_LOCATION_STOCK_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES products (id);

ALTER TABLE location_stock
    ADD CONSTRAINT FK_LOCATION_STOCK_ON_LOCATION FOREIGN KEY (location_id) REFERENCES storage_locations (id);

CREATE TABLE stock_transfers
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_id       BIGINT                                  NOT NULL,
    from_location_id BIGINT,
    to_location_id   BIGINT,
    quantity         INTEGER                                 NOT NULL,
    moved_by         BIGINT,
    transfer_type    VARCHAR(32)                             NOT NULL,
    note             TEXT,
    created_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_stock_transfers PRIMARY KEY (id)
);

ALTER TABLE stock_transfers
    ADD CONSTRAINT FK_STOCK_TRANSFERS_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES products (id);

ALTER TABLE stock_transfers
    ADD CONSTRAINT FK_STOCK_TRANSFERS_ON_FROM_LOCATION FOREIGN KEY (from_location_id) REFERENCES storage_locations (id);

ALTER TABLE stock_transfers
    ADD CONSTRAINT FK_STOCK_TRANSFERS_ON_TO_LOCATION FOREIGN KEY (to_location_id) REFERENCES storage_locations (id);

ALTER TABLE stock_transfers
    ADD CONSTRAINT FK_STOCK_TRANSFERS_ON_MOVED_BY FOREIGN KEY (moved_by) REFERENCES users (id);

CREATE INDEX idx_stock_transfers_product_created ON stock_transfers (product_id, created_at);

-- Seed: shop floor holds all default roles at launch (ADR-004 / ADR-006).
INSERT INTO storage_locations (name, type, active, is_default_receiving, is_walk_in_sale_source,
                               is_ecommerce_fulfilment_source, version, created_at, updated_at)
VALUES ('Shop Floor', 'SHOP_FLOOR', TRUE, TRUE, TRUE, TRUE, 0, now(), now()),
       ('Store Room 1', 'STORE_ROOM', TRUE, FALSE, FALSE, FALSE, 0, now(), now());

-- Backfill: all existing stock starts on the shop floor; staff redistribute via transfers.
INSERT INTO location_stock (product_id, location_id, quantity_on_hand, version, created_at, updated_at)
SELECT p.id,
       (SELECT sl.id FROM storage_locations sl WHERE sl.name = 'Shop Floor'),
       p.stock_quantity,
       0,
       now(),
       now()
FROM products p
WHERE p.stock_quantity > 0;
